config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "cookings#index"
  resources :cookings do
    collection do
      get 'search'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cooking.rb
class Cooking < ApplicationRecord
  
  belongs_to :user
  has_one_attached :image

  with_options presence: true do
    validates :cooking_name
    validates :explanation
    validates :ingredients1 
    validates :quantity1 
  end

  def self.search(search)
    if search != ""
      Cooking.where('explanation LIKE(?)', "%#{search}%")
    else
      Cooking.all
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cookings

  VALID_PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i

  with_options presence: true do
    validates :nick_name
    validates :password,            length: {minimum: 6 },
                                    format: { with: VALID_PASSWORD_REGEX},
                                    confirmation: true
    validates :email,               uniqueness: true

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nick_name, :email, :password,])
  end

end

app/controllers/cookings_controller.rb
class CookingsController < ApplicationController
  
  def index
    @cookings = Cooking.all
  end

  def new
    @cooking = Cooking.new
  end

  def create
    @cooking = Cooking.new(cooking_params)
    if @cooking.save
       redirect_to root_path
    else
      render :new
    end
  end

  def show
    @cooking = Cooking.find(params[:id])
  end

  def search
    @cookings = Cooking.search(params[:keyword])
  end

  private

  def cooking_params
    params.require(:cooking).permit(:image, :cooking_name, :explanation, :ingredients1, :quantity1, :ingredients2, :quantity2, :ingredients3, :quantity3, :ingredients4, :quantity4, :ingredients5, :quantity5, :ingredients6, :quantity6, :ingredients7, :quantity7, :ingredients8, :quantity8, :ingredients9, :quantity9, :ingredients0, :quantity0, :name).merge(user_id: current_user.id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cookings_helper.rb
module CookingsHelper
end

app/views/cookings/index.html.erb
<div class='header'>
  <%= link_to image_tag("gobou.png", size: '150x40'), "/" %>

  <ul class='login-out'>
    <% if user_signed_in? %>
      <div id="nav">
        <li class= "nickname-top"><a href=""><span class="en"><%=current_user.nick_name%></span><span class="jp">マイページへ</span></a></li>
      </div>
      <li><%= link_to image_tag("logout.png", class: "logout-icon"), destroy_user_session_path, method: :delete, class: "logout" %></li>
    <% else %>  
      <li><%= link_to image_tag("login.png", class: "login-icon"), new_user_session_path, class: "login" %></li>
    <% end %>
  </ul> 

</div>


<div class='title-contents'>
  <h3 class='title'>
    Fridge!で冷蔵庫を整理しよう！！
  </h3>
  <%= form_with(url: search_cookings_path, method: :get, class: "search", local: true) do |f| %>
    <%= f.text_field :keyword, placeholder: "材料名", class: "search-input" %>
    <%= f.submit "レシピ検索", class: "search-btn" %>
  <% end %>
</div>


<div class='feature'>
  <h2 class='feature-title'>
    Fridge!の特徴
  </h2>

  <ul class='feature-list'>
    <li class='list'>
      <%= image_tag "kensaku.jpg" , class: "image" %>
      <h3 class='list-text'>
        余った食材で検索
      </h3>
      <p class='list-description'>
        検索した食材を使ったレシピを一覧表示できます。
      </p>
    </li>
    <li class='list'>
      <%= image_tag "osieru.jpg" , class: "image" %>
      <h3 class='list-text'>
        自分のレシピを教える
      </h3>
      <p class='list-description'>
        検索はもちろん自分のレシピをアップすることができます。
      </p>
    </li>
    <li class='list'>
      <%= image_tag "okiniiri.jpg" , class: "image" %>
      <h3 class='list-text'>
        お気に入りに保存
      </h3>
      <p class='list-description'>
        お気に入りに保存したレシピをすぐに見る事ができます。
      </p>
    </li>
  </ul>
</div>


<div class='show'>
  <h2 class='show-title'>
    〜最新レシピ〜
  </h2>
  <%= link_to 'レシピ投稿', new_cooking_path , class: "subtitle" %>
  <ul class='cooking-list'>
    <% @cookings.each do |cooking| %>
      <li class='show-list'>
        <%= link_to cooking_path(cooking) do %>
          <div>
            <%= image_tag cooking.image, class: "cooking-img" %>
          </div>
          <div class='cooking-name'>
            <%= cooking.cooking_name %>
          </div>
        <% end %>
      </li>
    <% end %>
  </ul>
</div>

<p class="inc">
  <%= link_to image_tag('gobou.png' , size: '130x30'), "/" %>
  <div>
    ©︎Fridge!,Inc.
  </div>
</p>

app/views/cookings/new.html.erb
<%= link_to image_tag("gobou.png", size: '150x40'), "/", class: "rogo-cooking-new"%>
<div class="cooking-new-all">
  <%= form_with model:@cooking, url:cookings_path, local: true do |f| %>

    <h2 class="make-title">
      自分のレシピを教える
    </h2>
    <div class="make-image">
      完成イメージ
    </div>
    <div class="cooking-image">
      <%= f.file_field :image, id:"cooking-image" %>
    </div>


  <div class="new-cooking">
    <div class="cooking-title">
      料理名
    </div>
      <%= f.text_field :cooking_name, class:"cooking-title-text", placeholder:"40文字まで", maxlength:"40" %> 
  </div>

  <div class= "ingredients">
    <div class= "ingredients-line">
      <div>
        材料名
      </div>
      <div>
        <%= f.text_field :ingredients1, placeholder:"例: 人参", class: "cooking-form"%> 
      </div>
    </div>
    <div class= "ingredients-line">
      <div>
        分量
      </div>
      <div>
        <%= f.text_field :quantity1, placeholder:"例: 1本", class: "cooking-form"%> 
      </div>
    </div>
  </div>

  <div class= "ingredients">
    <div class= "ingredients-line">
      <div>
        材料名
      </div>
      <div>
        <%= f.text_field :ingredients2, placeholder:"例: 豚肉", class: "cooking-form"%> 
      </div>
    </div>
    <div class= "ingredients-line">
      <div>
        分量
      </div>
      <div>
        <%= f.text_field :quantity2, placeholder:"例: 200g", class: "cooking-form"%> 
      </div>
    </div>
  </div>
  
  <div class= "ingredients">
    <div class= "ingredients-line">
      <div>
        材料名
      </div>
      <div>
        <%= f.text_field :ingredients3, placeholder:"例: じゃがいも", class: "cooking-form"%> 
      </div>
    </div>
    <div class= "ingredients-line">
      <div>
        分量
      </div>
      <div>
        <%= f.text_field :quantity3, placeholder:"例: 3個", class: "cooking-form"%> 
      </div>
    </div>
  </div>

  <div class= "ingredients">
    <div class= "ingredients-line">
      <div>
        材料名
      </div>
      <div>
        <%= f.text_field :ingredients4, placeholder:"例: 玉ねぎ", class: "cooking-form"%> 
      </div>
    </div>
    <div class= "ingredients-line">
      <div>
        分量
      </div>
      <div>
        <%= f.text_field :quantity4, placeholder:"例: 1個", class: "cooking-form"%> 
      </div>
    </div>
  </div>

  <div class= "ingredients">
    <div class= "ingredients-line">
      <div>
        材料名
      </div>
      <div>
        <%= f.text_field :ingredients5, placeholder:"例: 水", class: "cooking-form"%> 
      </div>
    </div>
    <div class= "ingredients-line">
      <div>
        分量
      </div>
      <div>
        <%= f.text_field :quantity5, placeholder:"例: 200g", class: "cooking-form"%> 
      </div>
    </div>
  </div>

  <div class= "ingredients">
    <div class= "ingredients-line">
      <div>
        材料名
      </div>
      <div>
        <%= f.text_field :ingredients6, placeholder:"例: 醤油", class: "cooking-form"%> 
      </div>
    </div>
    <div class= "ingredients-line">
      <div>
        分量
      </div>
      <div>
        <%= f.text_field :quantity6, placeholder:"例: 30g", class: "cooking-form"%> 
      </div>
    </div>
  </div>

  <div class= "ingredients">
    <div class= "ingredients-line">
      <div>
        材料名
      </div>
      <div>
        <%= f.text_field :ingredients7, placeholder:"例: 酒", class: "cooking-form"%> 
      </div>
    </div>
    <div class= "ingredients-line">
      <div>
        分量
      </div>
      <div>
        <%= f.text_field :quantity7, placeholder:"例: 30g", class: "cooking-form"%> 
      </div>
    </div>
  </div>

  <div class= "ingredients">
    <div class= "ingredients-line">
      <div>
        材料名
      </div>
      <div>
        <%= f.text_field :ingredients8, placeholder:"例: 砂糖", class: "cooking-form"%> 
      </div>
    </div>
    <div class= "ingredients-line">
      <div>
        分量
      </div>
      <div>
        <%= f.text_field :quantity8, placeholder:"例: 30g", class: "cooking-form"%> 
      </div>
    </div>
  </div>

  <div class= "ingredients">
    <div class= "ingredients-line">
      <div>
        材料名
      </div>
      <div>
        <%= f.text_field :ingredients9, placeholder:"例: みりん", class: "cooking-form"%> 
      </div>
    </div>
    <div class= "ingredients-line">
      <div>
        分量
      </div>
      <div>
        <%= f.text_field :quantity9, placeholder:"例: 30g", class: "cooking-form"%> 
      </div>
    </div>
  </div>

  <div class= "ingredients">
    <div class= "ingredients-line">
      <div>
        材料名
      </div>
      <div>
        <%= f.text_field :ingredients0, placeholder:"例: 顆粒和風だし", class: "cooking-form"%> 
      </div>
    </div>
    <div class= "ingredients-line">
      <div>
        分量
      </div>
      <div>
        <%= f.text_field :quantity0, placeholder:"例: 7g", class: "cooking-form"%> 
      </div>
    </div>
  </div>




  <div class="items-explain">
    <div class="weight-bold-text">
      調理の説明
    </div>
      <%= f.text_area :explanation, class:"cooking-text", id:"item-info", placeholder:"調理の説明（必須 1,000文字まで）" ,rows:"7" ,maxlength:"1000" %> 
  </div>


  <div class="post-btn-contents">
    <%= f.submit "投稿する" ,class:"post-btn" %>
    <%=link_to 'もどる', root_path, class:"back-btn" %>
  </div>
  <% end %>
</div>

app/views/cookings/search.html.erb
<%= form_with(url: search_cookings_path, method: :get, class: "search", local: true) do |f| %>
  <%= f.text_field :keyword, placeholder: "材料名", class: "search-input" %>
  <%= f.submit "レシピ検索", class: "search-btn" %>
<% end %>
<div class="contents-row">
  <% @cookings.each do |cooking| %>
    <%= link_to cooking_path(cooking.id) do %>
      <div class="search-show">
        <%= image_tag cooking.image, class: "search-image"%>
        <%= cooking.cooking_name %>
      </div>
    <% end %> 
  <% end %>
</div>

 

app/views/cookings/show.html.erb
<div class="item-show">
  <%= link_to image_tag("gobou.png", size: '150x40'), "/", class: "rogo-show"%>

    <%= form_with(url: "", method: :get, class: "search", local: true) do |f| %>
      <%= f.text_field :keyword, placeholder: "材料名", class: "search-input" %>
      <%= f.submit "レシピ検索", class: "search-btn" %>
    <% end %>
    <h2 class="name">
      <%= @cooking.cooking_name%>
    </h2>
  <div>
    <%= image_tag @cooking.image ,class:"item-box-img" %>
  </div>
    <table class="detail-table">
      <th class="detail-item">材料</th>
      <td class="detail-value">
        <% if @cooking.ingredients1.present?%>
          <P><%= @cooking.ingredients1 %>・・・<%= @cooking.quantity1 %></p>
        <%end%>
        <% if @cooking.ingredients2?%>
          <P><%= @cooking.ingredients2 %>・・・<%= @cooking.quantity2 %></p>
        <%end%>
        <% if @cooking.ingredients3.present?%>
          <P><%= @cooking.ingredients3 %>・・・<%= @cooking.quantity3 %></p>
        <%end%>
        <% if @cooking.ingredients4.present?%>
          <P><%= @cooking.ingredients4 %>・・・<%= @cooking.quantity4 %></p>
        <%end%>
        <% if @cooking.ingredients5.present?%>
          <P><%= @cooking.ingredients5 %>・・・<%= @cooking.quantity5 %></p>
        <%end%>
        <% if @cooking.ingredients6.present?%>
          <P><%= @cooking.ingredients6 %>・・・<%= @cooking.quantity6 %></p>
        <%end%>
        <% if @cooking.ingredients7.present?%>
          <P><%= @cooking.ingredients7 %>・・・<%= @cooking.quantity7 %></p>
        <%end%>
        <% if @cooking.ingredients8.present?%>
          <P><%= @cooking.ingredients8 %>・・・<%= @cooking.quantity8 %></p>
        <%end%>
        <% if @cooking.ingredients9.present?%>
          <P><%= @cooking.ingredients9 %>・・・<%= @cooking.quantity9 %></p>
        <%end%>
        <% if @cooking.ingredients0.present?%>
          <P><%= @cooking.ingredients0 %>・・・<%= @cooking.quantity0 %></p>
        <%end%>
      </td>
      <tr>
        <th class="detail-item">調理説明</th>
        <td class="detail-value"><%= @cooking.explanation %></td>
      </tr>
    </table>
    <%= link_to :back do %>
      <div class="back-btn">
        もどる
      </div>
    <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fridge</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>